// default package
// Generated 17 Aug, 2015 5:58:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * Employeedata generated by hbm2java
 */
package hbm;

public class Employeedata implements java.io.Serializable {

	private Integer id;
	private String address;
	private Integer age;
	private String name;
	private Long sal;

	public Employeedata() {
	}

	public Employeedata(String address, Integer age, String name, Long sal) {
		this.address = address;
		this.age = age;
		this.name = name;
		this.sal = sal;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getSal() {
		return this.sal;
	}

	public void setSal(Long sal) {
		this.sal = sal;
	}

}
